server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
          - Path=/hotels/**
        - id: tour-service
          uri: lb://tour-service
          predicates:
          - Path=/tours/**
               
    
eureka:
  client:
    serviceUrl:
      defautZone: http://localhost:8761/eureka/
      
management:
  tracing:
    sampling:
      probability: 1.0
      

